version: '3'

tasks:
  migrate:
    - dbmate create
    - dbmate up

  prepare:
    - docker compose up

  start:
    - go run *.go

  atlas_apply:
    - atlas schema apply --env local

  atlas_inspect:
    - atlas schema inspect --env local
